- name: Installing common packages between clusters
  hosts: cluster
  become: yes
  roles:
  - role: common-configurations
    retries: 3
    delay: 10 
    vars:
      install_version: "1.30"
  
- name: performing the kubeadm init ops on master
  hosts: masters
  become: yes
  roles:
  - master
  
- name: caching the join command to be used later in worker nodes
  hosts: masters
  become: yes
  gather_facts: false
  roles:
  - cluster_join

- name: executing the cached join command on workers
  hosts: workers
  become: yes
  roles:
  - cluster_join

- name: Installing miscellaneous - k9s, crictl, ciliumcli, metlalb
  hosts: masters
  become: yes
  gather_facts: false
  roles:
  - others
# No idempotency unlike other roles, which can be run multiple times - handle with care, preferably take a snapshot of the virtualbox instance
# Most of the time it may fail here, comment out rest of the roles before rerun & maybe run the selective part of the role, or run it manually

# kubectl create deployment nginx-web-server --image=nginx
# kubectl expose deployment nginx-web-server --port=80 --target-port=80 --type=LoadBalancer