- name: Turn off swap
  command: "swapoff -a"

- name: Turn off swap permanently by editing fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*'
    line: '# \g<0>'

- name: create containerd systemctl file at modules-load.d
  copy:
    src: 'files/containerd.conf'
    dest: '/etc/modules-load.d/k8s.conf'    

- name: create kubernetes systemctl file at sysctl.d
  copy:
    src: 'files/kubernetes.conf'
    dest: '/etc/sysctl.d/kubernetes.conf'

- name: install misc binaries
  apt:
    name: 
    - curl
    - gnupg2
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    state: present

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg

- name: Import Docker GPG key
  shell: gpg --dearmor /tmp/docker.gpg > /etc/apt/trusted.gpg.d/docker.gpg

- name: install misc binaries
  apt:
    name: 
    - containerd.io
    state: present