- name: Turn off swap
  command: "swapoff -a"

- name: Turn off swap permanently by editing fstab entry
  lineinfile:
    path: /etc/fstab
    regexp: '^/swap.img.*'
    line: '#/swap.img       none    swap    sw      0       0'

- name: create containerd systemctl file at modules-load.d
  copy:
    src: 'files/containerd.conf'
    dest: '/etc/modules-load.d/containerd.conf'    

- name: overlay
  command: "modprobe overlay"

- name: br_netfilter
  command: "modprobe br_netfilter"      

- name: create kubernetes systemctl file at sysctl.d
  copy:
    src: 'files/kubernetes.conf'
    dest: '/etc/sysctl.d/kubernetes.conf'

- name: Apply sysctl settings
  become: yes
  command: sysctl --system

- name: install misc binaries
  apt:
    name: 
    - curl
    - gnupg2
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    state: present

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg

- name: Import Docker GPG key
  shell: gpg --dearmor </tmp/docker.gpg >/etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker APT repository
  become: yes
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    create: yes

- name: install containerd
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: populate containerd defaults
  shell: containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1

- name: Update containerd config
  become: yes
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '\s*SystemdCgroup\s*=\s*false'
    line: 'SystemdCgroup = true'

- name: Restart and enable containerd service
  become: yes
  systemd:
    name: containerd
    state: restarted
    enabled: yes

- name: Download Kubernetes key
  get_url:
    url: 'https://pkgs.k8s.io/core:/stable:/{{ kub_version }}/deb/Release.key'
    dest: /tmp/kubernetesRelease.key

- name: Import Kubernetes GPG key
  shell: gpg --dearmor < /tmp/kubernetesRelease.key > /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes APT repository
  become: yes
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kub_version }}/deb/ /"
    create: yes  

- name: install kubernetes binaries
  apt:
    name: 
    - kubeadm
    - kubelet
    - kubectl
    state: present
    update_cache: yes