- name: Check if swap is enabled
  command: swapon --summary
  register: swap_status
  ignore_errors: true
# - debug:
#     msg: "{{ swap_status }}"
- name: First time config of vms
  block:
  - name: Update /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: '{{ hostvars[item].ansible_host }} {{ item }}'
      state: present
    with_items: "{{ groups['all'] }}"
    when: inventory_hostname != item  
  - name: copy k8s module file for overlay & br_netfilter
    copy:
      src: 'files/mod-k8s.conf'
      dest: '/etc/modules-load.d/k8s.conf'
  - name: copy k8s systemctl file for ip fwd
    copy:
      src: 'files/sysctl-k8s.conf'
      dest: '/etc/sysctl.d/k8s.conf'
  - name: modprobe overlay
    command: "modprobe overlay"
  - name: modprobe br_netfilter
    command: "modprobe br_netfilter"
  - name: Load sysctl
    command: "sysctl --system"
  - name: Turn off swap
    command: "swapoff -a"
  - name: Turn off swap permanently by editing fstab entry
    lineinfile:
      path: /etc/fstab
      regexp: '^.*swap.*'
      line: '# \g<0>'
  when: swap_status.stdout != "" 

- name: Ensure docker.list exists
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: touch
    mode: '0644'
- name: Update docker entry in /etc/apt/sources.list.d/docker.list
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable'
    state: present
- name: Import GPG key for the repository Docker
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    keyring: '/etc/apt/keyrings/docker.gpg'
    state: present
- name: install containerd
  apt:
    name: 
    - containerd.io
    state: present
    update_cache: 'True'
- name: copy config.toml for containerd
  copy:
    src: 'files/config.toml'
    dest: '/etc/containerd/config.toml'
- name: Restart containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: true  

- name: Ensure kubeadm, kubelet, kubectl
  include_tasks: kubeadm_setup.yml
  loop:
    - '1.28'
    - '1.29'
    - '1.30'
    - '1.31'
- name: Get the available versions of kubeadm
  shell: "apt-cache madison kubeadm | grep {{ install_version }} | head -1 | awk '{print $3}'"
  register: kubeadm_version
  run_once: true
- name: Get the available versions of kubelet
  shell: "apt-cache madison kubelet | grep {{ install_version }} | head -1 | awk '{print $3}'"
  register: kubelet_version
  run_once: true
- name: Get the available versions of kubectl
  shell: "apt-cache madison kubectl | grep {{ install_version }} | head -1 | awk '{print $3}'"
  register: kubectl_version
  run_once: true
- name: install kubeadm kubelet & kubectl
  apt:
    name: 
    - kubelet={{ kubeadm_version.stdout }}
    - kubeadm={{ kubelet_version.stdout }}
    - kubectl={{ kubectl_version.stdout }}
    state: present
    update_cache: 'True'
- name: hold kubelet & kubeadm
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - 'kubelet'
    - 'kubeadm'
- name: Set KUBELET_EXTRA_ARGS in /etc/default/kubelet
  lineinfile:
    path: '/etc/default/kubelet'
    line: 'KUBELET_EXTRA_ARGS=--node-ip={{ ansible_ssh_host }}'
    regexp: '^KUBELET_EXTRA_ARGS='
    state: present
    create: yes
