- name: Ensure helm-stable-debian.list exists
  file:
    path: /etc/apt/sources.list.d/helm-stable-debian.list
    state: touch
    mode: '0644'

- name: Download helm
  shell: | 
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | tee /usr/share/keyrings/helm.gpg > /dev/null
- name: Update helm entry in /etc/apt/sources.list.d/helm-stable-debian.list
  lineinfile:
    path: /etc/apt/sources.list.d/helm-stable-debian.list
    line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main'
    state: present

- name: install and helm
  apt:
    name: 
    - zsh
    - helm
    - bat
    state: present
    update_cache: 'True'

- name: isntalling k9s
  snap:
    name:
    - k9s
- name: Create softlink for k9s bin
  shell: | 
    ln -s /snap/k9s/current/bin/k9s /snap/bin/
    ln -s /usr/bin/batcat /usr/local/bin/bat

# - name: Download cilum #Although downloaded, not usable
#   shell: | 
#     curl -L "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz" -o /tmp/cilium-linux-amd64.tar.gz 
#     tar zxvf /tmp/cilium-linux-amd64.tar.gz -C /usr/local/bin 
#     rm /tmp/cilium-linux-amd64.tar.gz
#    cilium install --set ipam.operator.clusterPoolIPv4PodCIDRList=["172.16.0.0/16"]
#    sleep 2m
- name: Install cilium via helm repo
  become_user: manju 
  register: helm_debug
  shell: |   
    helm repo add cilium https://helm.cilium.io/ && echo "helm added cilium repo"
    helm install cilium cilium/cilium --version 1.16.1 --namespace kube-system --set ipam.operator.clusterPoolIPv4PodCIDRList=172.16.0.0/16 && echo "helm install cilium - done"
    sleep 3m  
- debug: var=helm_debug.stdout_lines    

- name: Metal-lb -- Modify kube-proxy configmap and apply native file
  become_user: manju  
  shell: |
    kubectl get configmap kube-proxy -n kube-system -o yaml | \
    sed -e "s/strictARP: false/strictARP: true/" | \
    kubectl apply -f - -n kube-system
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml
- name: Metal-lb -- copy the metalb manifests
  copy:
    src: '{{ item }}'
    dest: '/tmp/{{ item | basename }}'
  with_fileglob:
    - 'files/*'          
- name: Metal-lb -- Apply Kubernetes manifests from local machine to remote system
  become_user: manju  
  shell: |
    kubectl apply -f /tmp/metallb-ipadd-pool.yaml
    kubectl apply -f /tmp/metallb-pool-advertise.yaml