- name: Check if Kubernetes cluster is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_initialized
- name: Initialize Kubernetes master
  register: initcluster
  #command: "kubeadm init --apiserver-advertise-address={{ master_ip }} --apiserver-cert-extra-sans={{ master_ip }} --pod-network-cidr={{ pod_cidr }} --node-name {{ master_hostname }}"
  command: "kubeadm init --apiserver-advertise-address={{ master_ip }} --pod-network-cidr={{ pod_cidr }}"
  when: not kubeadm_initialized.stat.exists
- debug: var=initcluster.stdout_lines
- name: Create .kube directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory
    mode: 0755
  become: no
- name: Copy admin.conf to .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"