master_ip: "{{ groups['masters'] | map('extract', hostvars, 'ansible_host') | first }}"
master_hostname: "{{ groups['masters'] | map('extract', hostvars, 'inventory_hostname') | first }}"
pod_cidr: "192.168.0.0/16"